# docker-compose setup for development setup.
# Use quickstart.docker-compose.yaml if you just want to try out Kelemetry.
# Use the helm chart if you want to deploy in production.
version: "3"
services:
  # ETCD cache storage, only required if etcd cache is used
  etcd:
    image: quay.io/coreos/etcd:v3.2
    entrypoint: [etcd]
    command:
      - -name=main
      - -advertise-client-urls=http://etcd:2379
      - -listen-client-urls=http://0.0.0.0:2379
      - -initial-advertise-peer-urls=http://etcd:2380
      - -listen-peer-urls=http://0.0.0.0:2380
      - -initial-cluster-state=new
      - -initial-cluster=main=http://etcd:2380
      - -initial-cluster-token=etcd-cluster-1
      - -data-dir=/var/run/etcd/default.etcd
    volumes:
      - etcd:/var/run/etcd/default.etcd
    restart: always
    ports:
      - 0.0.0.0:2379:2379
    deploy:
      resources:
        limits:
          memory: 1G
  # Web frontend for trace view.
  jaeger-query:
    image: jaegertracing/jaeger-query:1.42
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: host.docker.internal:17271 # run on host directly
    ports:
      - 0.0.0.0:16686:16686
    restart: always
  # OTLP collector that writes to Badger
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.42
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: remote-badger:17271
    ports:
      - 0.0.0.0:4317:4317
    restart: always
  # Backend badger storage
  # Feel free to override environment.SPAN_STORAGE_TYPE to other storages given the proper configuration.
  remote-badger:
    image: jaegertracing/jaeger-remote-storage:1.42
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_KEY: /mnt/badger/key
      BADGER_DIRECTORY_VALUE: /mnt/badger/data
    ports:
      - 0.0.0.0:17271:17271
    volumes:
      - badger:/mnt/badger
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  # Web frontend for raw trace database view.
  jaeger-query-raw:
    image: jaegertracing/jaeger-query:1.42
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: remote-badger:17271
    ports:
      - 0.0.0.0:26686:16686
    restart: always

volumes:
  etcd: {}
  badger: {}
